import {
  File, Code, Palette, FileJson, Globe, BookOpen, Hash, FileCode,
  FileCog, Terminal, Type, Binary, Package, Layout, Database, Settings,
  Container, ScrollText, Lock, Key, GitBranch, FileText, Table, Music,
  Video, Presentation, Hammer, Braces, Cpu, Coffee, Notebook, Image,
} from 'lucide-react';

import type { LucideIcon } from 'lucide-react';

type IconMapping = { icon: LucideIcon; color: string };

const EXT_MAP: Record<string, IconMapping> = {
  java: { icon: Coffee, color: '#b07219' },
  kt: { icon: Code, color: '#7F52FF' },
  kts: { icon: Code, color: '#7F52FF' },
  py: { icon: Code, color: '#3572A5' },
  go: { icon: Code, color: '#00ADD8' },
  rs: { icon: Code, color: '#dea584' },
  rb: { icon: Code, color: '#701516' },
  php: { icon: Code, color: '#4F5D95' },
  c: { icon: Code, color: '#555555' },
  h: { icon: Code, color: '#555555' },
  cpp: { icon: Code, color: '#f34b7d' },
  cc: { icon: Code, color: '#f34b7d' },
  cxx: { icon: Code, color: '#f34b7d' },
  hpp: { icon: Code, color: '#f34b7d' },
  hxx: { icon: Code, color: '#f34b7d' },
  cs: { icon: Code, color: '#178600' },
  swift: { icon: Code, color: '#F05138' },
  dart: { icon: Code, color: '#00B4AB' },
  scala: { icon: Code, color: '#dc322f' },
  sc: { icon: Code, color: '#dc322f' },
  groovy: { icon: Code, color: '#e69c56' },
  gvy: { icon: Code, color: '#e69c56' },
  gy: { icon: Code, color: '#e69c56' },
  lua: { icon: Code, color: '#000080' },
  hs: { icon: Code, color: '#5e5086' },
  erl: { icon: Code, color: '#B83998' },
  hrl: { icon: Code, color: '#B83998' },
  ex: { icon: Code, color: '#6e4a7e' },
  exs: { icon: Code, color: '#6e4a7e' },
  clj: { icon: Code, color: '#db5855' },
  cljs: { icon: Code, color: '#db5855' },
  cljc: { icon: Code, color: '#db5855' },
  edn: { icon: Code, color: '#db5855' },
  jl: { icon: Code, color: '#a270ba' },
  zig: { icon: Code, color: '#ec915c' },
  nim: { icon: Code, color: '#ffe953' },
  nims: { icon: Code, color: '#ffe953' },
  cr: { icon: Code, color: '#000100' },
  fs: { icon: Code, color: '#b845fc' },
  fsx: { icon: Code, color: '#b845fc' },
  fsi: { icon: Code, color: '#b845fc' },
  vb: { icon: Code, color: '#945db7' },
  ts: { icon: Code, color: '#3178c6' },
  tsx: { icon: Code, color: '#3178c6' },
  js: { icon: Code, color: '#3178c6' },
  jsx: { icon: Code, color: '#3178c6' },
  mjs: { icon: Code, color: '#3178c6' },
  cjs: { icon: Code, color: '#3178c6' },
  css: { icon: Palette, color: '#e34c97' },
  scss: { icon: Palette, color: '#e34c97' },
  less: { icon: Palette, color: '#e34c97' },
  sass: { icon: Palette, color: '#e34c97' },
  json: { icon: FileJson, color: '#f5a623' },
  html: { icon: Globe, color: '#e44d26' },
  htm: { icon: Globe, color: '#e44d26' },
  md: { icon: BookOpen, color: '#519aba' },
  markdown: { icon: BookOpen, color: '#519aba' },
  yaml: { icon: Hash, color: '#cb171e' },
  yml: { icon: Hash, color: '#cb171e' },
  xml: { icon: FileCode, color: '#e37933' },
  toml: { icon: FileCog, color: '#9b9b9b' },
  sh: { icon: Terminal, color: '#4eaa51' },
  bash: { icon: Terminal, color: '#4eaa51' },
  zsh: { icon: Terminal, color: '#4eaa51' },
  bat: { icon: Terminal, color: '#4eaa51' },
  cmd: { icon: Terminal, color: '#4eaa51' },
  ps1: { icon: Terminal, color: '#4eaa51' },
  ttf: { icon: Type, color: '#f97316' },
  otf: { icon: Type, color: '#f97316' },
  woff: { icon: Type, color: '#f97316' },
  woff2: { icon: Type, color: '#f97316' },
  eot: { icon: Type, color: '#f97316' },
  exe: { icon: Binary, color: '#8b8b8b' },
  dll: { icon: Binary, color: '#8b8b8b' },
  so: { icon: Binary, color: '#8b8b8b' },
  dylib: { icon: Binary, color: '#8b8b8b' },
  zip: { icon: Package, color: '#8b8b8b' },
  tar: { icon: Package, color: '#8b8b8b' },
  gz: { icon: Package, color: '#8b8b8b' },
  rar: { icon: Package, color: '#8b8b8b' },
  '7z': { icon: Package, color: '#8b8b8b' },
  bz2: { icon: Package, color: '#8b8b8b' },
  xz: { icon: Package, color: '#8b8b8b' },
  vue: { icon: Layout, color: '#42b883' },
  svelte: { icon: Layout, color: '#42b883' },
  db: { icon: Database, color: '#f29111' },
  sqlite: { icon: Database, color: '#f29111' },
  sql: { icon: Database, color: '#f29111' },
  properties: { icon: Settings, color: '#6d8086' },
  conf: { icon: Settings, color: '#6d8086' },
  config: { icon: Settings, color: '#6d8086' },
  cfg: { icon: Settings, color: '#6d8086' },
  ini: { icon: Settings, color: '#6d8086' },
  log: { icon: ScrollText, color: '#6d8086' },
  logs: { icon: ScrollText, color: '#6d8086' },
  env: { icon: Lock, color: '#f5a623' },
  pem: { icon: Key, color: '#f5a623' },
  crt: { icon: Key, color: '#f5a623' },
  cer: { icon: Key, color: '#f5a623' },
  p12: { icon: Key, color: '#f5a623' },
  pfx: { icon: Key, color: '#f5a623' },
  gitignore: { icon: GitBranch, color: '#f05033' },
  gitattributes: { icon: GitBranch, color: '#f05033' },
  gitkeep: { icon: GitBranch, color: '#f05033' },
  pdf: { icon: FileText, color: '#f40f02' },
  doc: { icon: FileText, color: '#2957a4' },
  docx: { icon: FileText, color: '#2957a4' },
  odt: { icon: FileText, color: '#2957a4' },
  xls: { icon: Table, color: '#207245' },
  xlsx: { icon: Table, color: '#207245' },
  csv: { icon: Table, color: '#207245' },
  ods: { icon: Table, color: '#207245' },
  ppt: { icon: Presentation, color: '#c43e1c' },
  pptx: { icon: Presentation, color: '#c43e1c' },
  odp: { icon: Presentation, color: '#c43e1c' },
  mp3: { icon: Music, color: '#a074c4' },
  wav: { icon: Music, color: '#a074c4' },
  ogg: { icon: Music, color: '#a074c4' },
  flac: { icon: Music, color: '#a074c4' },
  aac: { icon: Music, color: '#a074c4' },
  m4a: { icon: Music, color: '#a074c4' },
  mp4: { icon: Video, color: '#a074c4' },
  avi: { icon: Video, color: '#a074c4' },
  mkv: { icon: Video, color: '#a074c4' },
  mov: { icon: Video, color: '#a074c4' },
  wmv: { icon: Video, color: '#a074c4' },
  webm: { icon: Video, color: '#a074c4' },
  mpg: { icon: Video, color: '#a074c4' },
  mpeg: { icon: Video, color: '#a074c4' },
  m4v: { icon: Video, color: '#a074c4' },
  gradle: { icon: Hammer, color: '#02303a' },
  proto: { icon: FileCode, color: '#4285f4' },
  graphql: { icon: Braces, color: '#e10098' },
  gql: { icon: Braces, color: '#e10098' },
  graphqls: { icon: Braces, color: '#e10098' },
  prisma: { icon: Database, color: '#5a67d8' },
  asm: { icon: Cpu, color: '#8b8b8b' },
  tf: { icon: Settings, color: '#7B42BC' },
  tfvars: { icon: Settings, color: '#7B42BC' },
  terragrunt: { icon: Settings, color: '#7B42BC' },
  ipynb: { icon: Notebook, color: '#da6c2e' },
  rst: { icon: BookOpen, color: '#519aba' },
  adoc: { icon: BookOpen, color: '#519aba' },
  asciidoc: { icon: BookOpen, color: '#519aba' },
  tex: { icon: FileText, color: '#3D6117' },
  latex: { icon: FileText, color: '#3D6117' },
  png: { icon: Image, color: '#a074c4' },
  jpg: { icon: Image, color: '#a074c4' },
  jpeg: { icon: Image, color: '#a074c4' },
  gif: { icon: Image, color: '#a074c4' },
  bmp: { icon: Image, color: '#a074c4' },
  tiff: { icon: Image, color: '#a074c4' },
  webp: { icon: Image, color: '#a074c4' },
  ico: { icon: Image, color: '#a074c4' },
  svg: { icon: Image, color: '#ffb13b' },
  psd: { icon: Palette, color: '#a074c4' },
  ai: { icon: Palette, color: '#a074c4' },
  sketch: { icon: Palette, color: '#a074c4' },
  fig: { icon: Palette, color: '#a074c4' },
  lock: { icon: Lock, color: '#3178c6' },
  key: { icon: Key, color: '#f5a623' },
};

const NAME_MAP: Record<string, IconMapping> = {
  dockerfile: { icon: Container, color: '#2496ed' },
  'dockerfile.dev': { icon: Container, color: '#2496ed' },
  'dockerfile.prod': { icon: Container, color: '#2496ed' },
  'docker-compose.yml': { icon: Container, color: '#2496ed' },
  'docker-compose.yaml': { icon: Container, color: '#2496ed' },
  '.gitignore': { icon: GitBranch, color: '#f05033' },
  '.gitattributes': { icon: GitBranch, color: '#f05033' },
  '.gitkeep': { icon: GitBranch, color: '#f05033' },
  '.npmrc': { icon: Package, color: '#cb171e' },
  '.env': { icon: Lock, color: '#f5a623' },
  'package.json': { icon: Package, color: '#cb171e' },
  'package-lock.json': { icon: Package, color: '#cb171e' },
  'pnpm-lock.yaml': { icon: Package, color: '#cb171e' },
  'tsconfig.json': { icon: Package, color: '#cb171e' },
  'vite.config.ts': { icon: Package, color: '#cb171e' },
  'rollup.config.js': { icon: Package, color: '#cb171e' },
  'webpack.config.js': { icon: Package, color: '#cb171e' },
  'pnpm-workspace.yaml': { icon: Package, color: '#cb171e' },
  'readme.md': { icon: FileText, color: '#519aba' },
  'changelog.md': { icon: FileText, color: '#519aba' },
  'license.md': { icon: FileText, color: '#519aba' },
  'contributing.md': { icon: FileText, color: '#519aba' },
  'yarn.lock': { icon: Lock, color: '#3178c6' },
  makefile: { icon: Hammer, color: '#427819' },
  gnumakefile: { icon: Hammer, color: '#427819' },
  'makefile.am': { icon: Hammer, color: '#427819' },
  'cmakelists.txt': { icon: Hammer, color: '#064f8c' },
  'cmake.cache.txt': { icon: Hammer, color: '#064f8c' },
};

const DEFAULT_ICON: IconMapping = { icon: File, color: 'var(--text-muted)' };

export const getFileIcon = (fileName: string): IconMapping => {
  const lowerName = fileName.toLowerCase();
  const nameMatch = NAME_MAP[lowerName];
  if (nameMatch) return nameMatch;

  if (lowerName.startsWith('.env')) {
    return { icon: Lock, color: '#f5a623' };
  }

  const ext = fileName.includes('.') ? fileName.split('.').pop()?.toLowerCase() : '';
  if (ext) {
    const extMatch = EXT_MAP[ext];
    if (extMatch) return extMatch;
  }

  return DEFAULT_ICON;
};
